[package]
name = "bevy-compute"
version = "0.1.0"
edition = "2021"

[lib]
name = "bevy_compute"
crate-type = ["lib"]

[dependencies]
bevy = "0.16.1"
bevy_platform = "0.16.1"

[[example]]
name = "life"
